const GAME_PACKS = {
    animals: {
        name: 'Animaux',
        pairs: [
            { word: 'Lion', undercover: 'Tigre' },
            { word: 'Chat', undercover: 'Félin' },
            { word: 'Chien', undercover: 'Loup' },
            { word: 'Papillon', undercover: 'Abeille' },
            { word: 'Poisson', undercover: 'Dauphin' },
            { word: 'Oiseau', undercover: 'Aigle' },
            { word: 'Souris', undercover: 'Rat' },
            { word: 'Éléphant', undercover: 'Rhinocéros' },
            { word: 'Girafe', undercover: 'Zèbre' },
            { word: 'Panda', undercover: 'Ours' },
            { word: 'Serpent', undercover: 'Python' }
        ]
    },
    vehicles: {
        name: 'Véhicules',
        pairs: [
            { word: 'Voiture', undercover: 'Automobile' },
            { word: 'Avion', undercover: 'Hélicoptère' },
            { word: 'Bateau', undercover: 'Navire' },
            { word: 'Vélo', undercover: 'Bicyclette' },
            { word: 'Train', undercover: 'Rail' },
            { word: 'Bus', undercover: 'Autocar' },
            { word: 'Moto', undercover: 'Motocyclette' },
            { word: 'Camion', undercover: 'Poids lourd' },
            { word: 'Tramway', undercover: 'Métro aérien' },
            { word: 'Voilier', undercover: 'Yacht' }
        ]
    },
    nature: {
        name: 'Nature',
        pairs: [
            { word: 'Soleil', undercover: 'Étoile' },
            { word: 'Lune', undercover: 'Satellite' },
            { word: 'Mer', undercover: 'Océan' },
            { word: 'Montagne', undercover: 'Pic' },
            { word: 'Arbre', undercover: 'Forêt' },
            { word: 'Fleur', undercover: 'Rose' },
            { word: 'Rivière', undercover: 'Fleuve' },
            { word: 'Lac', undercover: 'Étang' },
            { word: 'Désert', undercover: 'Sahara' },
            { word: 'Forêt', undercover: 'Jungle' }
        ]
    },
    food: {
        name: 'Nourriture',
        pairs: [
            { word: 'Pizza', undercover: 'Pâtes' },
            { word: 'Burger', undercover: 'Sandwich' },
            { word: 'Sushi', undercover: 'Rouleau' },
            { word: 'Salade', undercover: 'Légumes' },
            { word: 'Gâteau', undercover: 'Pâtisserie' },
            { word: 'Chocolat', undercover: 'Bonbon' },
            { word: 'Café', undercover: 'Espresso' },
            { word: 'Thé', undercover: 'Tisane' },
            { word: 'Vin', undercover: 'Alcool' },
            { word: 'Bière', undercover: 'Breuvage' },
            { word: 'Fromage', undercover: 'Lait' },
            { word: 'Beurre', undercover: 'Graisse' },
            { word: 'Pain', undercover: 'Farine' },
            { word: 'Riz', undercover: 'Céréale' },
            { word: 'Pommes de terre', undercover: 'Tubercule' },
            { word: 'Tomate', undercover: 'Fruit' },
            { word: 'Oignon', undercover: 'Bulbe' },
            { word: 'Œuf', undercover: 'Protéine' },
            { word: 'Viande', undercover: 'Steak' },
            { word: 'Poisson', undercover: 'Fruits de mer' },
        ]
    },
    movies: {
        name: 'Films',
        pairs: [
            { word: 'Cinéma', undercover: 'Film' },
            { word: 'Acteur', undercover: 'Comédien' },
            { word: 'Réalisateur', undercover: 'Metteur en scène' },
            { word: 'Scène', undercover: 'Plan' },
            { word: 'Action', undercover: 'Cascade' },
            { word: 'Comédie', undercover: 'Humour' },
            { word: 'Drame', undercover: 'Tragédie' },
            { word: 'Horreur', undercover: 'Peur' },
            { word: 'Thriller', undercover: 'Suspense' },
            { word: 'Romance', undercover: 'Amour' },
            { word: 'Aventure', undercover: 'Quête' },
            { word: 'Science-fiction', undercover: 'Futur' },
            { word: 'Fantastique', undercover: 'Magie' },
            { word: 'Animation', undercover: 'Dessin animé' },
            { word: 'Oscar', undercover: 'Prix' },
            { word: 'Popcorn', undercover: 'Snack' },
            { word: 'Écran', undercover: 'Projection' },
            { word: 'Projecteur', undercover: 'Lumière' },
            { word: 'Hollywood', undercover: 'Tinseltown' },
            { word: 'Bande sonore', undercover: 'Musique' }
        ]
    },
    cooking: {
        name: 'Cuisine',
        pairs: [
            { word: 'Cuisine', undercover: 'Gastronomie' },
            { word: 'Cuisinier', undercover: 'Chef' },
            { word: 'Couteau', undercover: 'Lame' },
            { word: 'Poêle', undercover: 'Casserole' },
            { word: 'Four', undercover: 'Fourneau' },
            { word: 'Réfrigérateur', undercover: 'Frigo' },
            { word: 'Recette', undercover: 'Formule' },
            { word: 'Ingrédient', undercover: 'Composant' },
            { word: 'Sel', undercover: 'Assaisonnement' },
            { word: 'Poivre', undercover: 'Épice' },
            { word: 'Sauce', undercover: 'Condiment' },
            { word: 'Huile', undercover: 'Graisse' },
            { word: 'Sucre', undercover: 'Douceur' },
            { word: 'Farine', undercover: 'Poudre' },
            { word: 'Levure', undercover: 'Ferment' },
            { word: 'Mélanger', undercover: 'Remuer' },
            { word: 'Cuire', undercover: 'Réchauffer' },
            { word: 'Rôtir', undercover: 'Griller' },
            { word: 'Bouillir', undercover: 'Chauffer' },
            { word: 'Égoutter', undercover: 'Filtrer' }
        ]
    },
    sports: {
        name: 'Sports',
        pairs: [
            { word: 'Football', undercover: 'Soccer' },
            { word: 'Basketball', undercover: 'Ballon' },
            { word: 'Tennis', undercover: 'Raquette' },
            { word: 'Natation', undercover: 'Piscine' },
            { word: 'Course', undercover: 'Sprint' },
            { word: 'Vélo', undercover: 'Cyclisme' },
            { word: 'Ski', undercover: 'Montagne' },
            { word: 'Surf', undercover: 'Vague' },
            { word: 'Boxe', undercover: 'Combat' },
            { word: 'Judo', undercover: 'Martial' },
            { word: 'Yoga', undercover: 'Fitness' },
            { word: 'Gym', undercover: 'Musculation' },
            { word: 'Équitation', undercover: 'Cheval' },
            { word: 'Escalade', undercover: 'Rocher' },
            { word: 'Plongée', undercover: 'Océan' },
            { word: 'Handball', undercover: 'Équipe' },
            { word: 'Volley', undercover: 'Filet' },
            { word: 'Badminton', undercover: 'Raquette' },
            { word: 'Golf', undercover: 'Trou' },
            { word: 'Tir à l\'arc', undercover: 'Archerie' }
        ]
    },
    places: {
        name: 'Lieux',
        pairs: [
            { word: 'Plage', undercover: 'Sable' },
            { word: 'Montagne', undercover: 'Sommet' },
            { word: 'Forêt', undercover: 'Arbre' },
            { word: 'Désert', undercover: 'Dune' },
            { word: 'Ville', undercover: 'Métropole' },
            { word: 'Village', undercover: 'Hameau' },
            { word: 'Château', undercover: 'Forteresse' },
            { word: 'Église', undercover: 'Cathédrale' },
            { word: 'Musée', undercover: 'Galerie' },
            { word: 'Bibliothèque', undercover: 'Librairie' },
            { word: 'Zoo', undercover: 'Safari' },
            { word: 'Parc', undercover: 'Jardin' },
            { word: 'Gare', undercover: 'Station' },
            { word: 'Aéroport', undercover: 'Terminal' },
            { word: 'Hôtel', undercover: 'Motel' },
            { word: 'Restaurant', undercover: 'Bistro' },
            { word: 'Café', undercover: 'Brasserie' },
            { word: 'Magasin', undercover: 'Boutique' },
            { word: 'Marché', undercover: 'Bazar' },
            { word: 'Stade', undercover: 'Arène' }
        ]
    },
    music: {
        name: 'Musique',
        pairs: [
            { word: 'Piano', undercover: 'Clavier' },
            { word: 'Guitare', undercover: 'Cordes' },
            { word: 'Batterie', undercover: 'Percussion' },
            { word: 'Trompette', undercover: 'Cuivre' },
            { word: 'Violon', undercover: 'Archet' },
            { word: 'Chanteur', undercover: 'Chœur' },
            { word: 'Chanson', undercover: 'Mélodie' },
            { word: 'Rythme', undercover: 'Tempo' },
            { word: 'Note', undercover: 'Tonalité' },
            { word: 'Accord', undercover: 'Harmonie' },
            { word: 'Concert', undercover: 'Festival' },
            { word: 'Album', undercover: 'Disque' },
            { word: 'Artiste', undercover: 'Musicien' },
            { word: 'Genre', undercover: 'Style' },
            { word: 'Rock', undercover: 'Musique alternative' },
            { word: 'Pop', undercover: 'Variété' },
            { word: 'Jazz', undercover: 'Improvisation' },
            { word: 'Classique', undercover: 'Symphonie' },
            { word: 'Rap', undercover: 'Hip-hop' },
            { word: 'Électronique', undercover: 'Synthétiseur' }
        ]
    },
    technology: {
        name: 'Technologie',
        pairs: [
            { word: 'Ordinateur', undercover: 'Processeur' },
            { word: 'Téléphone', undercover: 'Mobile' },
            { word: 'Tablette', undercover: 'Écran' },
            { word: 'Internet', undercover: 'Réseau' },
            { word: 'Email', undercover: 'Message' },
            { word: 'Application', undercover: 'Logiciel' },
            { word: 'Écran', undercover: 'Moniteur' },
            { word: 'Clavier', undercover: 'Touche' },
            { word: 'Souris', undercover: 'Curseur' },
            { word: 'Batterie', undercover: 'Charge' },
            { word: 'Câble', undercover: 'Fil' },
            { word: 'Wifi', undercover: 'Signal' },
            { word: 'Caméra', undercover: 'Photo' },
            { word: 'Microphone', undercover: 'Son' },
            { word: 'Haut-parleur', undercover: 'Audio' },
            { word: 'Processeur', undercover: 'CPU' },
            { word: 'Mémoire', undercover: 'RAM' },
            { word: 'Stockage', undercover: 'Disque dur' },
            { word: 'Code', undercover: 'Programmation' },
            { word: 'Bug', undercover: 'Erreur' }
        ]
    }
};
